@server=http://localhost:3001

GET {{server}}/api/blogs HTTP/1.1

###

GET {{server}}/api/users HTTP/1.1

###


POST {{server}}/api/blogs HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1vbmdvIiwiaWQiOiI1YmM3NTQwNmVkNzcyYTJhMGRlM2QyMTQiLCJpYXQiOjE1Mzk4MTI0NzZ9.2yr7_IdfsvKaJ4UbUE0SjuNBwy2MMlZy263J5qiHcwA

{
    "title": "Notes on Penicillin",
    "author": "Mongo",
    "url": "http://127.0.0.1",
    "likes": 42,
    "userId": "5bc75406ed772a2a0de3d214"
}

###
POST {{server}}/api/blogs HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1vbmdvIiwiaWQiOiI1YmM3NTQwNmVkNzcyYTJhMGRlM2QyMTQiLCJpYXQiOjE1Mzk4MTI0NzZ9.2yr7_IdfsvKaJ4UbUE0SjuNBwy2MMlZy263J5qiHcwA

{
    "title": "Notes on Nietschze",
    "author": "Mongo & Johnson",
    "url": "http://127.0.0.1",
    "likes": 100,
    "userId": "5bc75406ed772a2a0de3d214"
}


###

POST {{server}}/api/users HTTP/1.1
content-type: application/json

{
    "username": "mongo",
    "name": "Mongo from Blazing Saddles",
    "adult": false,
    "password": "sekret" 
}

###

DELETE {{server}}/api/blogs/5bba1581e59947d2a4c99e6d HTTP/1.1


####

POST {{server}}/api/login HTTP/1.1
Content-Type: application/json

{
    "username": "mongo",
    "password": "sekret"
}


### comment


POST {{server}}/api/blogs/5bc7ad5d6a5d0e33864a5295/comments HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1vbmdvIiwiaWQiOiI1YmM3NTQwNmVkNzcyYTJhMGRlM2QyMTQiLCJpYXQiOjE1NDI1NDA1NTJ9.Lg5yOykY5VVw9OIeVdXCnu2MaID-1URowOMyh_h95ns

{
    "comment": "nice article"
}
